name: spanish-game
channels: 
  - conda-forge
dependencies:
  - python=3.10
  - pip

  - pip:
    - -e .

  - ipython
  - ipykernel
  - numpy
  - pandas
  - openpyxl
  - black
  - flake8
  - pytest
  - inquirer
  - pydantic
  - bcrypt
